version: "3"

services:
  cv:
    build: .
    image: opencv_pool_tracker
    command: python
    volumes:
      - .:/code
  notebook:
    build: notebook
    volumes:
      - ./notebook:/work
      - ./out/protoshape/interim:/work/data
    ports:
      - "8888:8888"
