version: "3"

services:
  cv:
    build: .
    image: opencv_pool_tracker
    command: python
    volumes:
      - .:/code
    environment:
      - AWS_ACCESS_KEY_ID=AKIAWNQH4SVBIALFLW74
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_DEFAULT_REGION=eu-west-1
  notebook:
    build: notebook
    volumes:
      - ./notebook:/work
      - ./out:/work/out
      - ./in:/work/in
    ports:
      - "8888:8888"
